/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DetectionRouteImport } from './routes/detection'
import { Route as MapRouteImport } from './routes/map'
import { Route as RailwayRouteImport } from './routes/railway'
import { Route as SpeedRouteImport } from './routes/speed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionRoute = DetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const RailwayRoute = RailwayRouteImport.update({
  id: '/railway',
  path: '/railway',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedRoute = SpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/detection': typeof DetectionRoute
  '/map': typeof MapRoute
  '/railway': typeof RailwayRoute
  '/speed': typeof SpeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/detection': typeof DetectionRoute
  '/map': typeof MapRoute
  '/railway': typeof RailwayRoute
  '/speed': typeof SpeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/detection': typeof DetectionRoute
  '/map': typeof MapRoute
  '/railway': typeof RailwayRoute
  '/speed': typeof SpeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analytics' | '/detection' | '/map' | '/railway' | '/speed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/detection' | '/map' | '/railway' | '/speed'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/detection'
    | '/map'
    | '/railway'
    | '/speed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DetectionRoute: typeof DetectionRoute
  MapRoute: typeof MapRoute
  RailwayRoute: typeof RailwayRoute
  SpeedRoute: typeof SpeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detection': {
      id: '/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof DetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/railway': {
      id: '/railway'
      path: '/railway'
      fullPath: '/railway'
      preLoaderRoute: typeof RailwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed': {
      id: '/speed'
      path: '/speed'
      fullPath: '/speed'
      preLoaderRoute: typeof SpeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DetectionRoute: DetectionRoute,
  MapRoute: MapRoute,
  RailwayRoute: RailwayRoute,
  SpeedRoute: SpeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
